
package ru.myrest.cb.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DailyInfoSoap", targetNamespace = "http://web.cbr.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DailyInfoSoap {


    /**
     * Сальдо операций ЦБ РФ по предоставлению/абсорбированию ликвидности (XMLDocument)
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.SaldoXMLResponse.SaldoXMLResult
     */
    @WebMethod(operationName = "SaldoXML", action = "http://web.cbr.ru/SaldoXML")
    @WebResult(name = "SaldoXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "SaldoXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.SaldoXML")
    @ResponseWrapper(localName = "SaldoXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.SaldoXMLResponse")
    public ru.myrest.cb.ws.client.SaldoXMLResponse.SaldoXMLResult saldoXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Ставка ROISfix (XMLDocument)
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.ROISfixXMLResponse.ROISfixXMLResult
     */
    @WebMethod(operationName = "ROISfixXML", action = "http://web.cbr.ru/ROISfixXML")
    @WebResult(name = "ROISfixXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "ROISfixXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.ROISfixXML")
    @ResponseWrapper(localName = "ROISfixXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.ROISfixXMLResponse")
    public ru.myrest.cb.ws.client.ROISfixXMLResponse.ROISfixXMLResult roiSfixXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Ставка Ruonia (XMLDocument)
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.RuoniaXMLResponse.RuoniaXMLResult
     */
    @WebMethod(operationName = "RuoniaXML", action = "http://web.cbr.ru/RuoniaXML")
    @WebResult(name = "RuoniaXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "RuoniaXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.RuoniaXML")
    @ResponseWrapper(localName = "RuoniaXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.RuoniaXMLResponse")
    public ru.myrest.cb.ws.client.RuoniaXMLResponse.RuoniaXMLResult ruoniaXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Депозиты банков в Банке России (млн. руб) (как xmlDocument)
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.OstatDepoXMLResponse.OstatDepoXMLResult
     */
    @WebMethod(operationName = "OstatDepoXML", action = "http://web.cbr.ru/OstatDepoXML")
    @WebResult(name = "OstatDepoXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "OstatDepoXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.OstatDepoXML")
    @ResponseWrapper(localName = "OstatDepoXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.OstatDepoXMLResponse")
    public ru.myrest.cb.ws.client.OstatDepoXMLResponse.OstatDepoXMLResult ostatDepoXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Депозиты банков в Банке России (млн. руб)
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.OstatDepoResponse.OstatDepoResult
     */
    @WebMethod(operationName = "OstatDepo", action = "http://web.cbr.ru/OstatDepo")
    @WebResult(name = "OstatDepoResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "OstatDepo", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.OstatDepo")
    @ResponseWrapper(localName = "OstatDepoResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.OstatDepoResponse")
    public ru.myrest.cb.ws.client.OstatDepoResponse.OstatDepoResult ostatDepo(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Ставка ROISfix (DataSet)
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.ROISfixResponse.ROISfixResult
     */
    @WebMethod(operationName = "ROISfix", action = "http://web.cbr.ru/ROISfix")
    @WebResult(name = "ROISfixResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "ROISfix", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.ROISfix")
    @ResponseWrapper(localName = "ROISfixResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.ROISfixResponse")
    public ru.myrest.cb.ws.client.ROISfixResponse.ROISfixResult roiSfix(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Ставка RUONIA (DataSet)
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.RuoniaResponse.RuoniaResult
     */
    @WebMethod(operationName = "Ruonia", action = "http://web.cbr.ru/Ruonia")
    @WebResult(name = "RuoniaResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Ruonia", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.Ruonia")
    @ResponseWrapper(localName = "RuoniaResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.RuoniaResponse")
    public ru.myrest.cb.ws.client.RuoniaResponse.RuoniaResult ruonia(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Международные резервы Российской Федерации, еженедельные значения (DataSet)
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.Mrrf7DResponse.Mrrf7DResult
     */
    @WebMethod(action = "http://web.cbr.ru/mrrf7D")
    @WebResult(name = "mrrf7DResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "mrrf7D", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.Mrrf7D")
    @ResponseWrapper(localName = "mrrf7DResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.Mrrf7DResponse")
    public ru.myrest.cb.ws.client.Mrrf7DResponse.Mrrf7DResult mrrf7D(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Международные резервы Российской Федерации, еженедельные значения  (XMLDocument)
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.Mrrf7DXMLResponse.Mrrf7DXMLResult
     */
    @WebMethod(action = "http://web.cbr.ru/mrrf7DXML")
    @WebResult(name = "mrrf7DXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "mrrf7DXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.Mrrf7DXML")
    @ResponseWrapper(localName = "mrrf7DXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.Mrrf7DXMLResponse")
    public ru.myrest.cb.ws.client.Mrrf7DXMLResponse.Mrrf7DXMLResult mrrf7DXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Задолженность кредитных организаций перед Банком России по операциям РЕПО в иностранной валюте (DataSet)
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.RepoDebtUSDResponse.RepoDebtUSDResult
     */
    @WebMethod(operationName = "RepoDebtUSD", action = "http://web.cbr.ru/RepoDebtUSD")
    @WebResult(name = "RepoDebtUSDResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "RepoDebtUSD", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.RepoDebtUSD")
    @ResponseWrapper(localName = "RepoDebtUSDResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.RepoDebtUSDResponse")
    public ru.myrest.cb.ws.client.RepoDebtUSDResponse.RepoDebtUSDResult repoDebtUSD(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Задолженность кредитных организаций перед Банком России по операциям РЕПО в иностранной валюте  (XMLDocument)
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.RepoDebtUSDXMLResponse.RepoDebtUSDXMLResult
     */
    @WebMethod(operationName = "RepoDebtUSDXML", action = "http://web.cbr.ru/RepoDebtUSDXML")
    @WebResult(name = "RepoDebtUSDXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "RepoDebtUSDXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.RepoDebtUSDXML")
    @ResponseWrapper(localName = "RepoDebtUSDXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.RepoDebtUSDXMLResponse")
    public ru.myrest.cb.ws.client.RepoDebtUSDXMLResponse.RepoDebtUSDXMLResult repoDebtUSDXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Международные резервы Российской Федерации, ежемесячные значения  (DataSet)
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.MrrfResponse.MrrfResult
     */
    @WebMethod(action = "http://web.cbr.ru/mrrf")
    @WebResult(name = "mrrfResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "mrrf", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.Mrrf")
    @ResponseWrapper(localName = "mrrfResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.MrrfResponse")
    public ru.myrest.cb.ws.client.MrrfResponse.MrrfResult mrrf(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Международные резервы Российской Федерации, ежемесячные значения  (XMLDocument)
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.MrrfXMLResponse.MrrfXMLResult
     */
    @WebMethod(action = "http://web.cbr.ru/mrrfXML")
    @WebResult(name = "mrrfXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "mrrfXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.MrrfXML")
    @ResponseWrapper(localName = "mrrfXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.MrrfXMLResponse")
    public ru.myrest.cb.ws.client.MrrfXMLResponse.MrrfXMLResult mrrfXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Сальдо операций ЦБ РФ по предоставлению/абсорбированию ликвидности (DataSet)
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.SaldoResponse.SaldoResult
     */
    @WebMethod(operationName = "Saldo", action = "http://web.cbr.ru/Saldo")
    @WebResult(name = "SaldoResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Saldo", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.Saldo")
    @ResponseWrapper(localName = "SaldoResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.SaldoResponse")
    public ru.myrest.cb.ws.client.SaldoResponse.SaldoResult saldo(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Получение новостей сервера (XMLDocument)
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.NewsInfoXMLResponse.NewsInfoXMLResult
     */
    @WebMethod(operationName = "NewsInfoXML", action = "http://web.cbr.ru/NewsInfoXML")
    @WebResult(name = "NewsInfoXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "NewsInfoXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.NewsInfoXML")
    @ResponseWrapper(localName = "NewsInfoXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.NewsInfoXMLResponse")
    public ru.myrest.cb.ws.client.NewsInfoXMLResponse.NewsInfoXMLResult newsInfoXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Операции на открытом рынке (как XMLDocument)
     * 
     * @return
     *     returns ru.myrest.cb.ws.client.OmodInfoXMLResponse.OmodInfoXMLResult
     */
    @WebMethod(operationName = "OmodInfoXML", action = "http://web.cbr.ru/OmodInfoXML")
    @WebResult(name = "OmodInfoXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "OmodInfoXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.OmodInfoXML")
    @ResponseWrapper(localName = "OmodInfoXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.OmodInfoXMLResponse")
    public ru.myrest.cb.ws.client.OmodInfoXMLResponse.OmodInfoXMLResult omodInfoXML();

    /**
     * Операции Банка России на рынке государственных ценных бумаг по поручению Министерства финансов Российской Федерации (как DataSet)
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.XVolResponse.XVolResult
     */
    @WebMethod(operationName = "XVol", action = "http://web.cbr.ru/XVol")
    @WebResult(name = "XVolResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "XVol", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.XVol")
    @ResponseWrapper(localName = "XVolResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.XVolResponse")
    public ru.myrest.cb.ws.client.XVolResponse.XVolResult xVol(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Операции Банка России на рынке государственных ценных бумаг по поручению Министерства финансов Российской Федерации  (XMLDocument)
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.XVolXMLResponse.XVolXMLResult
     */
    @WebMethod(operationName = "XVolXML", action = "http://web.cbr.ru/XVolXML")
    @WebResult(name = "XVolXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "XVolXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.XVolXML")
    @ResponseWrapper(localName = "XVolXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.XVolXMLResponse")
    public ru.myrest.cb.ws.client.XVolXMLResponse.XVolXMLResult xVolXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Получение основной информации - Ставка рефинансирования, золотовалютные резервы, денежная база, денежная масса (как XMLDocument)
     * 
     * @return
     *     returns ru.myrest.cb.ws.client.MainInfoXMLResponse.MainInfoXMLResult
     */
    @WebMethod(operationName = "MainInfoXML", action = "http://web.cbr.ru/MainInfoXML")
    @WebResult(name = "MainInfoXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "MainInfoXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.MainInfoXML")
    @ResponseWrapper(localName = "MainInfoXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.MainInfoXMLResponse")
    public ru.myrest.cb.ws.client.MainInfoXMLResponse.MainInfoXMLResult mainInfoXML();

    /**
     * Получение всей оперативной информации (XmlDocument) ver 11.03.2015
     * 
     * @return
     *     returns ru.myrest.cb.ws.client.AllDataInfoXMLResponse.AllDataInfoXMLResult
     */
    @WebMethod(operationName = "AllDataInfoXML", action = "http://web.cbr.ru/AllDataInfoXML")
    @WebResult(name = "AllDataInfoXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "AllDataInfoXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.AllDataInfoXML")
    @ResponseWrapper(localName = "AllDataInfoXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.AllDataInfoXMLResponse")
    public ru.myrest.cb.ws.client.AllDataInfoXMLResponse.AllDataInfoXMLResult allDataInfoXML();

    /**
     * Получение новостей сервера (DataSet)
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.NewsInfoResponse.NewsInfoResult
     */
    @WebMethod(operationName = "NewsInfo", action = "http://web.cbr.ru/NewsInfo")
    @WebResult(name = "NewsInfoResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "NewsInfo", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.NewsInfo")
    @ResponseWrapper(localName = "NewsInfoResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.NewsInfoResponse")
    public ru.myrest.cb.ws.client.NewsInfoResponse.NewsInfoResult newsInfo(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Валютный своп buy/sell overnight (XMLDocument)
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.SwapDynamicXMLResponse.SwapDynamicXMLResult
     */
    @WebMethod(operationName = "SwapDynamicXML", action = "http://web.cbr.ru/SwapDynamicXML")
    @WebResult(name = "SwapDynamicXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "SwapDynamicXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.SwapDynamicXML")
    @ResponseWrapper(localName = "SwapDynamicXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.SwapDynamicXMLResponse")
    public ru.myrest.cb.ws.client.SwapDynamicXMLResponse.SwapDynamicXMLResult swapDynamicXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Объем сделок «валютный своп» по продаже долларов США за рубли, заключенных Банком России (XMLDocument)
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.SwapInfoSellUSDVolXMLResponse.SwapInfoSellUSDVolXMLResult
     */
    @WebMethod(operationName = "SwapInfoSellUSDVolXML", action = "http://web.cbr.ru/SwapInfoSellUSDVolXML")
    @WebResult(name = "SwapInfoSellUSDVolXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "SwapInfoSellUSDVolXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.SwapInfoSellUSDVolXML")
    @ResponseWrapper(localName = "SwapInfoSellUSDVolXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.SwapInfoSellUSDVolXMLResponse")
    public ru.myrest.cb.ws.client.SwapInfoSellUSDVolXMLResponse.SwapInfoSellUSDVolXMLResult swapInfoSellUSDVolXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Объем сделок «валютный своп» по продаже долларов США за рубли, заключенных Банком России (DataSet) ver 21.11.2014
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.SwapInfoSellUSDVolResponse.SwapInfoSellUSDVolResult
     */
    @WebMethod(operationName = "SwapInfoSellUSDVol", action = "http://web.cbr.ru/SwapInfoSellUSDVol")
    @WebResult(name = "SwapInfoSellUSDVolResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "SwapInfoSellUSDVol", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.SwapInfoSellUSDVol")
    @ResponseWrapper(localName = "SwapInfoSellUSDVolResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.SwapInfoSellUSDVolResponse")
    public ru.myrest.cb.ws.client.SwapInfoSellUSDVolResponse.SwapInfoSellUSDVolResult swapInfoSellUSDVol(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Условия заключения сделок «валютный своп» по продаже долларов США за рубли (DataSet) ver 18.09.2014
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.SwapInfoSellUSDResponse.SwapInfoSellUSDResult
     */
    @WebMethod(operationName = "SwapInfoSellUSD", action = "http://web.cbr.ru/SwapInfoSellUSD")
    @WebResult(name = "SwapInfoSellUSDResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "SwapInfoSellUSD", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.SwapInfoSellUSD")
    @ResponseWrapper(localName = "SwapInfoSellUSDResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.SwapInfoSellUSDResponse")
    public ru.myrest.cb.ws.client.SwapInfoSellUSDResponse.SwapInfoSellUSDResult swapInfoSellUSD(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Условия заключения сделок «валютный своп» по продаже долларов США за рубли (как xmlDocument)
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.SwapInfoSellUSDXMLResponse.SwapInfoSellUSDXMLResult
     */
    @WebMethod(operationName = "SwapInfoSellUSDXML", action = "http://web.cbr.ru/SwapInfoSellUSDXML")
    @WebResult(name = "SwapInfoSellUSDXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "SwapInfoSellUSDXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.SwapInfoSellUSDXML")
    @ResponseWrapper(localName = "SwapInfoSellUSDXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.SwapInfoSellUSDXMLResponse")
    public ru.myrest.cb.ws.client.SwapInfoSellUSDXMLResponse.SwapInfoSellUSDXMLResult swapInfoSellUSDXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Стоимость бивалютной корзины (как xmlDocument)
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.BiCurBaseXMLResponse.BiCurBaseXMLResult
     */
    @WebMethod(operationName = "BiCurBaseXML", action = "http://web.cbr.ru/BiCurBaseXML")
    @WebResult(name = "BiCurBaseXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "BiCurBaseXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.BiCurBaseXML")
    @ResponseWrapper(localName = "BiCurBaseXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.BiCurBaseXMLResponse")
    public ru.myrest.cb.ws.client.BiCurBaseXMLResponse.BiCurBaseXMLResult biCurBaseXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Стоимость бивалютной корзины (DataSet) ver 03.12.2014
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.BiCurBaseResponse.BiCurBaseResult
     */
    @WebMethod(operationName = "BiCurBase", action = "http://web.cbr.ru/BiCurBase")
    @WebResult(name = "BiCurBaseResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "BiCurBase", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.BiCurBase")
    @ResponseWrapper(localName = "BiCurBaseResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.BiCurBaseResponse")
    public ru.myrest.cb.ws.client.BiCurBaseResponse.BiCurBaseResult biCurBase(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Структура бивалютной корзины  (как xmlDocument)
     * 
     * @return
     *     returns ru.myrest.cb.ws.client.BiCurBacketXMLResponse.BiCurBacketXMLResult
     */
    @WebMethod(operationName = "BiCurBacketXML", action = "http://web.cbr.ru/BiCurBacketXML")
    @WebResult(name = "BiCurBacketXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "BiCurBacketXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.BiCurBacketXML")
    @ResponseWrapper(localName = "BiCurBacketXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.BiCurBacketXMLResponse")
    public ru.myrest.cb.ws.client.BiCurBacketXMLResponse.BiCurBacketXMLResult biCurBacketXML();

    /**
     * Структура бивалютной корзины  (DataSet) ver 03.12.2014
     * 
     * @return
     *     returns ru.myrest.cb.ws.client.BiCurBacketResponse.BiCurBacketResult
     */
    @WebMethod(operationName = "BiCurBacket", action = "http://web.cbr.ru/BiCurBacket")
    @WebResult(name = "BiCurBacketResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "BiCurBacket", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.BiCurBacket")
    @ResponseWrapper(localName = "BiCurBacketResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.BiCurBacketResponse")
    public ru.myrest.cb.ws.client.BiCurBacketResponse.BiCurBacketResult biCurBacket();

    /**
     * Условия заключения сделок «валютный своп» по покупке долларов США и евро за рубли (DataSet) ver 31.07.2012
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.SwapDynamicResponse.SwapDynamicResult
     */
    @WebMethod(operationName = "SwapDynamic", action = "http://web.cbr.ru/SwapDynamic")
    @WebResult(name = "SwapDynamicResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "SwapDynamic", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.SwapDynamic")
    @ResponseWrapper(localName = "SwapDynamicResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.SwapDynamicResponse")
    public ru.myrest.cb.ws.client.SwapDynamicResponse.SwapDynamicResult swapDynamic(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Объем сделок 'валютный своп' Банка России (DataSet) ver 03.04.2014
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.SwapMonthTotalResponse.SwapMonthTotalResult
     */
    @WebMethod(operationName = "SwapMonthTotal", action = "http://web.cbr.ru/SwapMonthTotal")
    @WebResult(name = "SwapMonthTotalResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "SwapMonthTotal", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.SwapMonthTotal")
    @ResponseWrapper(localName = "SwapMonthTotalResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.SwapMonthTotalResponse")
    public ru.myrest.cb.ws.client.SwapMonthTotalResponse.SwapMonthTotalResult swapMonthTotal(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Объем сделок 'валютный своп' Банка России (как xmlDocument)
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.SwapMonthTotalXMLResponse.SwapMonthTotalXMLResult
     */
    @WebMethod(operationName = "SwapMonthTotalXML", action = "http://web.cbr.ru/SwapMonthTotalXML")
    @WebResult(name = "SwapMonthTotalXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "SwapMonthTotalXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.SwapMonthTotalXML")
    @ResponseWrapper(localName = "SwapMonthTotalXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.SwapMonthTotalXMLResponse")
    public ru.myrest.cb.ws.client.SwapMonthTotalXMLResponse.SwapMonthTotalXMLResult swapMonthTotalXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Ставки межбанковского кредитного рынка  (DataSet) ver 31.07.2012
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.MKRResponse.MKRResult
     */
    @WebMethod(operationName = "MKR", action = "http://web.cbr.ru/MKR")
    @WebResult(name = "MKRResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "MKR", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.MKR")
    @ResponseWrapper(localName = "MKRResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.MKRResponse")
    public ru.myrest.cb.ws.client.MKRResponse.MKRResult mkr(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Ставки межбанковского кредитного рынка (как xmlDocument)
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.MKRXMLResponse.MKRXMLResult
     */
    @WebMethod(operationName = "MKRXML", action = "http://web.cbr.ru/MKRXML")
    @WebResult(name = "MKRXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "MKRXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.MKRXML")
    @ResponseWrapper(localName = "MKRXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.MKRXMLResponse")
    public ru.myrest.cb.ws.client.MKRXMLResponse.MKRXMLResult mkrxml(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Требования Банка России к кредитным организациям (DataSet) ver 31.07.2012
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.DVResponse.DVResult
     */
    @WebMethod(operationName = "DV", action = "http://web.cbr.ru/DV")
    @WebResult(name = "DVResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "DV", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.DV")
    @ResponseWrapper(localName = "DVResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.DVResponse")
    public ru.myrest.cb.ws.client.DVResponse.DVResult dv(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Требования Банка России к кредитным организациям (как xmlDocument)
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.DVXMLResponse.DVXMLResult
     */
    @WebMethod(operationName = "DVXML", action = "http://web.cbr.ru/DVXML")
    @WebResult(name = "DVXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "DVXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.DVXML")
    @ResponseWrapper(localName = "DVXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.DVXMLResponse")
    public ru.myrest.cb.ws.client.DVXMLResponse.DVXMLResult dvxml(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Задолженность кредитных организаций перед Банком России по операциям прямого РЕПО (DataSet) ver 18.06.2014
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.RepoDebtResponse.RepoDebtResult
     */
    @WebMethod(operationName = "Repo_debt", action = "http://web.cbr.ru/Repo_debt")
    @WebResult(name = "Repo_debtResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Repo_debt", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.RepoDebt")
    @ResponseWrapper(localName = "Repo_debtResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.RepoDebtResponse")
    public ru.myrest.cb.ws.client.RepoDebtResponse.RepoDebtResult repoDebt(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Задолженность кредитных организаций перед Банком России по операциям прямого РЕПО (как xmlDocument)
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.RepoDebtXMLResponse.RepoDebtXMLResult
     */
    @WebMethod(operationName = "Repo_debtXML", action = "http://web.cbr.ru/Repo_debtXML")
    @WebResult(name = "Repo_debtXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Repo_debtXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.RepoDebtXML")
    @ResponseWrapper(localName = "Repo_debtXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.RepoDebtXMLResponse")
    public ru.myrest.cb.ws.client.RepoDebtXMLResponse.RepoDebtXMLResult repoDebtXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Отпускные цены Банка России на инвестиционные монеты (DataSet) ver 31.07.2012
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.CoinsBaseResponse.CoinsBaseResult
     */
    @WebMethod(operationName = "Coins_base", action = "http://web.cbr.ru/Coins_base")
    @WebResult(name = "Coins_baseResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Coins_base", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.CoinsBase")
    @ResponseWrapper(localName = "Coins_baseResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.CoinsBaseResponse")
    public ru.myrest.cb.ws.client.CoinsBaseResponse.CoinsBaseResult coinsBase(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Отпускные цены Банка России на инвестиционные монеты (как xmlDocument)
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.CoinsBaseXMLResponse.CoinsBaseXMLResult
     */
    @WebMethod(operationName = "Coins_baseXML", action = "http://web.cbr.ru/Coins_baseXML")
    @WebResult(name = "Coins_baseXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Coins_baseXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.CoinsBaseXML")
    @ResponseWrapper(localName = "Coins_baseXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.CoinsBaseXMLResponse")
    public ru.myrest.cb.ws.client.CoinsBaseXMLResponse.CoinsBaseXMLResult coinsBaseXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Фиксинги на драгоценные металлы (DataSet) ver 31.07.2012
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.FixingBaseResponse.FixingBaseResult
     */
    @WebMethod(operationName = "FixingBase", action = "http://web.cbr.ru/FixingBase")
    @WebResult(name = "FixingBaseResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "FixingBase", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.FixingBase")
    @ResponseWrapper(localName = "FixingBaseResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.FixingBaseResponse")
    public ru.myrest.cb.ws.client.FixingBaseResponse.FixingBaseResult fixingBase(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Фиксинги на драгоценные металлы (как xmlDocument)
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.FixingBaseXMLResponse.FixingBaseXMLResult
     */
    @WebMethod(operationName = "FixingBaseXML", action = "http://web.cbr.ru/FixingBaseXML")
    @WebResult(name = "FixingBaseXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "FixingBaseXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.FixingBaseXML")
    @ResponseWrapper(localName = "FixingBaseXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.FixingBaseXMLResponse")
    public ru.myrest.cb.ws.client.FixingBaseXMLResponse.FixingBaseXMLResult fixingBaseXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Ставки по кредиту 'overnight' (DataSet) ver 31.07.2012
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.OvernightResponse.OvernightResult
     */
    @WebMethod(operationName = "Overnight", action = "http://web.cbr.ru/Overnight")
    @WebResult(name = "OvernightResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Overnight", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.Overnight")
    @ResponseWrapper(localName = "OvernightResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.OvernightResponse")
    public ru.myrest.cb.ws.client.OvernightResponse.OvernightResult overnight(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Ставки по кредиту 'overnight' (как xmlDocument
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.OvernightXMLResponse.OvernightXMLResult
     */
    @WebMethod(operationName = "OvernightXML", action = "http://web.cbr.ru/OvernightXML")
    @WebResult(name = "OvernightXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "OvernightXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.OvernightXML")
    @ResponseWrapper(localName = "OvernightXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.OvernightXMLResponse")
    public ru.myrest.cb.ws.client.OvernightXMLResponse.OvernightXMLResult overnightXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * База данных по размещению бюджетных средств на депозиты коммерческих банков (DataSet) ver 31.07.2012
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.BauctionResponse.BauctionResult
     */
    @WebMethod(operationName = "Bauction", action = "http://web.cbr.ru/Bauction")
    @WebResult(name = "BauctionResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Bauction", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.Bauction")
    @ResponseWrapper(localName = "BauctionResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.BauctionResponse")
    public ru.myrest.cb.ws.client.BauctionResponse.BauctionResult bauction(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * База данных по размещению бюджетных средств на депозиты коммерческих банков (как xmlDocument
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.BauctionXMLResponse.BauctionXMLResult
     */
    @WebMethod(operationName = "BauctionXML", action = "http://web.cbr.ru/BauctionXML")
    @WebResult(name = "BauctionXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "BauctionXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.BauctionXML")
    @ResponseWrapper(localName = "BauctionXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.BauctionXMLResponse")
    public ru.myrest.cb.ws.client.BauctionXMLResponse.BauctionXMLResult bauctionXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Динамики ставок привлечения средств по депозитным операциям (как xmlDocument
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.DepoDynamicXMLResponse.DepoDynamicXMLResult
     */
    @WebMethod(operationName = "DepoDynamicXML", action = "http://web.cbr.ru/DepoDynamicXML")
    @WebResult(name = "DepoDynamicXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "DepoDynamicXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.DepoDynamicXML")
    @ResponseWrapper(localName = "DepoDynamicXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.DepoDynamicXMLResponse")
    public ru.myrest.cb.ws.client.DepoDynamicXMLResponse.DepoDynamicXMLResult depoDynamicXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Динамика ставок привлечения средств по депозитным операциям (DataSet) 
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.DepoDynamicResponse.DepoDynamicResult
     */
    @WebMethod(operationName = "DepoDynamic", action = "http://web.cbr.ru/DepoDynamic")
    @WebResult(name = "DepoDynamicResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "DepoDynamic", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.DepoDynamic")
    @ResponseWrapper(localName = "DepoDynamicResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.DepoDynamicResponse")
    public ru.myrest.cb.ws.client.DepoDynamicResponse.DepoDynamicResult depoDynamic(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Динамики сведений об остатках средств на корреспондентских счетах кредитных организаций (XMLDocument).
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.OstatDynamicXMLResponse.OstatDynamicXMLResult
     */
    @WebMethod(operationName = "OstatDynamicXML", action = "http://web.cbr.ru/OstatDynamicXML")
    @WebResult(name = "OstatDynamicXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "OstatDynamicXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.OstatDynamicXML")
    @ResponseWrapper(localName = "OstatDynamicXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.OstatDynamicXMLResponse")
    public ru.myrest.cb.ws.client.OstatDynamicXMLResponse.OstatDynamicXMLResult ostatDynamicXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Динамики сведений об остатках средств на корреспондентских счетах кредитных организаций (DataSet)!
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.OstatDynamicResponse.OstatDynamicResult
     */
    @WebMethod(operationName = "OstatDynamic", action = "http://web.cbr.ru/OstatDynamic")
    @WebResult(name = "OstatDynamicResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "OstatDynamic", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.OstatDynamic")
    @ResponseWrapper(localName = "OstatDynamicResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.OstatDynamicResponse")
    public ru.myrest.cb.ws.client.OstatDynamicResponse.OstatDynamicResult ostatDynamic(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Динамика учетных цен драгоценных металлов (как XMLDocument)
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.DragMetDynamicXMLResponse.DragMetDynamicXMLResult
     */
    @WebMethod(operationName = "DragMetDynamicXML", action = "http://web.cbr.ru/DragMetDynamicXML")
    @WebResult(name = "DragMetDynamicXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "DragMetDynamicXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.DragMetDynamicXML")
    @ResponseWrapper(localName = "DragMetDynamicXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.DragMetDynamicXMLResponse")
    public ru.myrest.cb.ws.client.DragMetDynamicXMLResponse.DragMetDynamicXMLResult dragMetDynamicXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Динамика учетных цен драгоценных металлов (DataSet)
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.DragMetDynamicResponse.DragMetDynamicResult
     */
    @WebMethod(operationName = "DragMetDynamic", action = "http://web.cbr.ru/DragMetDynamic")
    @WebResult(name = "DragMetDynamicResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "DragMetDynamic", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.DragMetDynamic")
    @ResponseWrapper(localName = "DragMetDynamicResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.DragMetDynamicResponse")
    public ru.myrest.cb.ws.client.DragMetDynamicResponse.DragMetDynamicResult dragMetDynamic(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Последняя дата публикации курсов валют как DateTime (ежедневные валюты)
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod(operationName = "GetLatestDateTime", action = "http://web.cbr.ru/GetLatestDateTime")
    @WebResult(name = "GetLatestDateTimeResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetLatestDateTime", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.GetLatestDateTime")
    @ResponseWrapper(localName = "GetLatestDateTimeResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.GetLatestDateTimeResponse")
    public XMLGregorianCalendar getLatestDateTime();

    /**
     * Последняя дата публикации курсов валют(ежемесячные валюты) - строка
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetLatestDate", action = "http://web.cbr.ru/GetLatestDate")
    @WebResult(name = "GetLatestDateResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetLatestDate", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.GetLatestDate")
    @ResponseWrapper(localName = "GetLatestDateResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.GetLatestDateResponse")
    public String getLatestDate();

    /**
     * Последняя дата публикации курсов валют как DateTime (ежемесячные валюты)
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod(operationName = "GetLatestDateTimeSeld", action = "http://web.cbr.ru/GetLatestDateTimeSeld")
    @WebResult(name = "GetLatestDateTimeSeldResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetLatestDateTimeSeld", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.GetLatestDateTimeSeld")
    @ResponseWrapper(localName = "GetLatestDateTimeSeldResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.GetLatestDateTimeSeldResponse")
    public XMLGregorianCalendar getLatestDateTimeSeld();

    /**
     * Последняя дата публикации курсов валют (ежемесячные валюты) - строка yyyyMMdd
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetLatestDateSeld", action = "http://web.cbr.ru/GetLatestDateSeld")
    @WebResult(name = "GetLatestDateSeldResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetLatestDateSeld", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.GetLatestDateSeld")
    @ResponseWrapper(localName = "GetLatestDateSeldResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.GetLatestDateSeldResponse")
    public String getLatestDateSeld();

    /**
     * Справочник по кодам валют (как XMLDocument)
     * 
     * @param seld
     * @return
     *     returns ru.myrest.cb.ws.client.EnumValutesXMLResponse.EnumValutesXMLResult
     */
    @WebMethod(operationName = "EnumValutesXML", action = "http://web.cbr.ru/EnumValutesXML")
    @WebResult(name = "EnumValutesXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "EnumValutesXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.EnumValutesXML")
    @ResponseWrapper(localName = "EnumValutesXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.EnumValutesXMLResponse")
    public ru.myrest.cb.ws.client.EnumValutesXMLResponse.EnumValutesXMLResult enumValutesXML(
        @WebParam(name = "Seld", targetNamespace = "http://web.cbr.ru/")
        boolean seld);

    /**
     * Справочник по кодам валют (как DataSet)
     * 
     * @param seld
     * @return
     *     returns ru.myrest.cb.ws.client.EnumValutesResponse.EnumValutesResult
     */
    @WebMethod(operationName = "EnumValutes", action = "http://web.cbr.ru/EnumValutes")
    @WebResult(name = "EnumValutesResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "EnumValutes", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.EnumValutes")
    @ResponseWrapper(localName = "EnumValutesResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.EnumValutesResponse")
    public ru.myrest.cb.ws.client.EnumValutesResponse.EnumValutesResult enumValutes(
        @WebParam(name = "Seld", targetNamespace = "http://web.cbr.ru/")
        boolean seld);

    /**
     * Последняя дата публикации редких валют от Thomson Reuters как DateTime (ежемесячные валюты)
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod(operationName = "GetLatestReutersDateTime", action = "http://web.cbr.ru/GetLatestReutersDateTime")
    @WebResult(name = "GetLatestReutersDateTimeResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetLatestReutersDateTime", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.GetLatestReutersDateTime")
    @ResponseWrapper(localName = "GetLatestReutersDateTimeResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.GetLatestReutersDateTimeResponse")
    public XMLGregorianCalendar getLatestReutersDateTime();

    /**
     * Справочник по кодам редких валют от Thomson Reuters (как XMLDocument)
     * 
     * @return
     *     returns ru.myrest.cb.ws.client.EnumReutersValutesXMLResponse.EnumReutersValutesXMLResult
     */
    @WebMethod(operationName = "EnumReutersValutesXML", action = "http://web.cbr.ru/EnumReutersValutesXML")
    @WebResult(name = "EnumReutersValutesXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "EnumReutersValutesXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.EnumReutersValutesXML")
    @ResponseWrapper(localName = "EnumReutersValutesXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.EnumReutersValutesXMLResponse")
    public ru.myrest.cb.ws.client.EnumReutersValutesXMLResponse.EnumReutersValutesXMLResult enumReutersValutesXML();

    /**
     * Справочник по кодам редких валют от Thomson Reuters  (как DataSet)
     * 
     * @return
     *     returns ru.myrest.cb.ws.client.EnumReutersValutesResponse.EnumReutersValutesResult
     */
    @WebMethod(operationName = "EnumReutersValutes", action = "http://web.cbr.ru/EnumReutersValutes")
    @WebResult(name = "EnumReutersValutesResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "EnumReutersValutes", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.EnumReutersValutes")
    @ResponseWrapper(localName = "EnumReutersValutesResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.EnumReutersValutesResponse")
    public ru.myrest.cb.ws.client.EnumReutersValutesResponse.EnumReutersValutesResult enumReutersValutes();

    /**
     * Получение ежедневных курсов редких валют от Thomson Reuters (как XMLDocument)
     * 
     * @param onDate
     * @return
     *     returns ru.myrest.cb.ws.client.GetReutersCursOnDateXMLResponse.GetReutersCursOnDateXMLResult
     */
    @WebMethod(operationName = "GetReutersCursOnDateXML", action = "http://web.cbr.ru/GetReutersCursOnDateXML")
    @WebResult(name = "GetReutersCursOnDateXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetReutersCursOnDateXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.GetReutersCursOnDateXML")
    @ResponseWrapper(localName = "GetReutersCursOnDateXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.GetReutersCursOnDateXMLResponse")
    public ru.myrest.cb.ws.client.GetReutersCursOnDateXMLResponse.GetReutersCursOnDateXMLResult getReutersCursOnDateXML(
        @WebParam(name = "On_date", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar onDate);

    /**
     * Получение ежедневных курсов редких валют от Thomson Reuters (как DataSet)
     * 
     * @param onDate
     * @return
     *     returns ru.myrest.cb.ws.client.GetReutersCursOnDateResponse.GetReutersCursOnDateResult
     */
    @WebMethod(operationName = "GetReutersCursOnDate", action = "http://web.cbr.ru/GetReutersCursOnDate")
    @WebResult(name = "GetReutersCursOnDateResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetReutersCursOnDate", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.GetReutersCursOnDate")
    @ResponseWrapper(localName = "GetReutersCursOnDateResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.GetReutersCursOnDateResponse")
    public ru.myrest.cb.ws.client.GetReutersCursOnDateResponse.GetReutersCursOnDateResult getReutersCursOnDate(
        @WebParam(name = "On_date", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar onDate);

    /**
     * Получение динамики ежедневных курсов редкой валюты от Thomson Reuters (как XMLDocument)
     * 
     * @param fromDate
     * @param numCode
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.GetReutersCursDynamicXMLResponse.GetReutersCursDynamicXMLResult
     */
    @WebMethod(operationName = "GetReutersCursDynamicXML", action = "http://web.cbr.ru/GetReutersCursDynamicXML")
    @WebResult(name = "GetReutersCursDynamicXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetReutersCursDynamicXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.GetReutersCursDynamicXML")
    @ResponseWrapper(localName = "GetReutersCursDynamicXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.GetReutersCursDynamicXMLResponse")
    public ru.myrest.cb.ws.client.GetReutersCursDynamicXMLResponse.GetReutersCursDynamicXMLResult getReutersCursDynamicXML(
        @WebParam(name = "FromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate,
        @WebParam(name = "NumCode", targetNamespace = "http://web.cbr.ru/")
        int numCode);

    /**
     * Получение динамики ежедневных курсов редкой валюты от Thomson Reuters (как DataSet)
     * 
     * @param fromDate
     * @param numCode
     * @param toDate
     * @return
     *     returns ru.myrest.cb.ws.client.GetReutersCursDynamicResponse.GetReutersCursDynamicResult
     */
    @WebMethod(operationName = "GetReutersCursDynamic", action = "http://web.cbr.ru/GetReutersCursDynamic")
    @WebResult(name = "GetReutersCursDynamicResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetReutersCursDynamic", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.GetReutersCursDynamic")
    @ResponseWrapper(localName = "GetReutersCursDynamicResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.GetReutersCursDynamicResponse")
    public ru.myrest.cb.ws.client.GetReutersCursDynamicResponse.GetReutersCursDynamicResult getReutersCursDynamic(
        @WebParam(name = "FromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate,
        @WebParam(name = "NumCode", targetNamespace = "http://web.cbr.ru/")
        int numCode);

    /**
     * Получение динамики ежедневных курсов валюты (как XMLDocument)
     * 
     * @param fromDate
     * @param toDate
     * @param valutaCode
     * @return
     *     returns ru.myrest.cb.ws.client.GetCursDynamicXMLResponse.GetCursDynamicXMLResult
     */
    @WebMethod(operationName = "GetCursDynamicXML", action = "http://web.cbr.ru/GetCursDynamicXML")
    @WebResult(name = "GetCursDynamicXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetCursDynamicXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.GetCursDynamicXML")
    @ResponseWrapper(localName = "GetCursDynamicXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.GetCursDynamicXMLResponse")
    public ru.myrest.cb.ws.client.GetCursDynamicXMLResponse.GetCursDynamicXMLResult getCursDynamicXML(
        @WebParam(name = "FromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate,
        @WebParam(name = "ValutaCode", targetNamespace = "http://web.cbr.ru/")
        String valutaCode);

    /**
     * Получение динамики ежедневных курсов валюты (как DataSet)
     * 
     * @param fromDate
     * @param toDate
     * @param valutaCode
     * @return
     *     returns ru.myrest.cb.ws.client.GetCursDynamicResponse.GetCursDynamicResult
     */
    @WebMethod(operationName = "GetCursDynamic", action = "http://web.cbr.ru/GetCursDynamic")
    @WebResult(name = "GetCursDynamicResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetCursDynamic", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.GetCursDynamic")
    @ResponseWrapper(localName = "GetCursDynamicResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.GetCursDynamicResponse")
    public ru.myrest.cb.ws.client.GetCursDynamicResponse.GetCursDynamicResult getCursDynamic(
        @WebParam(name = "FromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate,
        @WebParam(name = "ValutaCode", targetNamespace = "http://web.cbr.ru/")
        String valutaCode);

    /**
     * Получение ежедневных курсов валют (как XMLDocument)
     * 
     * @param onDate
     * @return
     *     returns ru.myrest.cb.ws.client.GetCursOnDateXMLResponse.GetCursOnDateXMLResult
     */
    @WebMethod(operationName = "GetCursOnDateXML", action = "http://web.cbr.ru/GetCursOnDateXML")
    @WebResult(name = "GetCursOnDateXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetCursOnDateXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.GetCursOnDateXML")
    @ResponseWrapper(localName = "GetCursOnDateXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.GetCursOnDateXMLResponse")
    public ru.myrest.cb.ws.client.GetCursOnDateXMLResponse.GetCursOnDateXMLResult getCursOnDateXML(
        @WebParam(name = "On_date", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar onDate);

    /**
     * Получение ежемесячных курсов валют !*устаревший! (как XMLDocument)
     * 
     * @param onDate
     * @return
     *     returns ru.myrest.cb.ws.client.GetSeldCursOnDateXMLResponse.GetSeldCursOnDateXMLResult
     */
    @WebMethod(operationName = "GetSeldCursOnDateXML", action = "http://web.cbr.ru/GetSeldCursOnDateXML")
    @WebResult(name = "GetSeldCursOnDateXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetSeldCursOnDateXML", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.GetSeldCursOnDateXML")
    @ResponseWrapper(localName = "GetSeldCursOnDateXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.GetSeldCursOnDateXMLResponse")
    public ru.myrest.cb.ws.client.GetSeldCursOnDateXMLResponse.GetSeldCursOnDateXMLResult getSeldCursOnDateXML(
        @WebParam(name = "On_date", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar onDate);

    /**
     * Получение ежемесячных курсов валют !*устаревший! (как DataSet)
     * 
     * @param onDate
     * @return
     *     returns ru.myrest.cb.ws.client.GetSeldCursOnDateResponse.GetSeldCursOnDateResult
     */
    @WebMethod(operationName = "GetSeldCursOnDate", action = "http://web.cbr.ru/GetSeldCursOnDate")
    @WebResult(name = "GetSeldCursOnDateResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetSeldCursOnDate", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.GetSeldCursOnDate")
    @ResponseWrapper(localName = "GetSeldCursOnDateResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.GetSeldCursOnDateResponse")
    public ru.myrest.cb.ws.client.GetSeldCursOnDateResponse.GetSeldCursOnDateResult getSeldCursOnDate(
        @WebParam(name = "On_date", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar onDate);

    /**
     * Получение ежедневных курсов валют (как DataSet)
     * 
     * @param onDate
     * @return
     *     returns ru.myrest.cb.ws.client.GetCursOnDateResponse.GetCursOnDateResult
     */
    @WebMethod(operationName = "GetCursOnDate", action = "http://web.cbr.ru/GetCursOnDate")
    @WebResult(name = "GetCursOnDateResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetCursOnDate", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.GetCursOnDate")
    @ResponseWrapper(localName = "GetCursOnDateResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.myrest.cb.ws.client.GetCursOnDateResponse")
    public ru.myrest.cb.ws.client.GetCursOnDateResponse.GetCursOnDateResult getCursOnDate(
        @WebParam(name = "On_date", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar onDate);

}
